# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'rake', '~> 13.0.1'
gem 'puma', '~> 4.3.0'

gem 'sinatra', '~> 2.1.0', require: 'sinatra/base'
gem 'sinatra-contrib', '~> 2.1.0'

gem 'config', '~> 2.2.1'

gem 'mongoid', '~> 7.0'
gem 'bunny', '~> 2.15.0'

gem 'dry-initializer', '~> 3.0.4'
gem 'dry-validation', '~> 1.6.0'

gem 'fast_jsonapi', '~> 1.5'

group :test do
  gem 'rspec', '~> 3.9.0'
  gem 'factory_bot', '~> 5.2.0'
  gem 'rack-test', '~> 1.1.0'
  gem 'database_cleaner-mongoid', '~> 2.0.0'
end

group :test, :development do
  gem 'pry-doc'
  gem 'pry-byebug'
  gem 'pry-rescue'
end
